Better error when comparing indexers
shouldly/shouldly pull request #779
Opened 2021-03-18 08:48 UTC by mcon

Previously you'd get a `TargetParameterCountException` when encountering an indexer, as indexers are properties with parameters, and the existing code assumed that no properties took parameters.

Ultimately there's no good way to compare indexers, as you can't obtain the full collection to compare, so this PR results in a better error in those cases.

2021-03-21 18:32 UTC, jnm2 reviewed
I'd approve but I had some questions that I'd like input on. I'm open to going multiple directions.

2021-03-21 18:32 UTC, jnm2 commented on src/Shouldly.Tests/ShouldBeEquivalentTo/ObjectScenario.cs
> +                    errorWithoutSource:"Comparing indexer property types is not supported");
Normally I'd rather think of this as not being a test failure but being a Shouldly API usage failure and throw `NotSupportedException`. What do you think?

Also just to nitpick, what do you think about `Comparing types that have indexers is not supported.`? I like having full sentences including end marks for user-facing messages coming out of a library, including XML docs and exception messages.

2021-03-21 18:32 UTC, jnm2 commented on src/Shouldly/ShouldlyExtensionMethods/ShouldBe/ObjectGraphTestExtensions.cs
> +                    throw new ShouldAssertException("Comparing indexer property types is not supported");
I have a slight preference for keeping related things together, and I think of the GetIndexParameters check and this `throw` as a logical unit. If you don't feel strongly, can you invert the `if` and remove the `else` nesting?

2021-03-22 15:16 UTC, jnm2 requested changes

2021-03-22 15:16 UTC, jnm2 commented on src/Shouldly.Tests/ShouldBeEquivalentTo/ObjectScenario.cs
> +            indexableObjectComparison.ShouldThrow<NotSupportedException>();
Could you add `.Message.ShouldBe(...)` on the end of this statement? It helps present a full picture of the user experience in the test code, and on rare occasions it has saved me from accidentally testing the wrong failure mode when the method throws the same exception type for two different reasons.

2021-03-22 15:16 UTC, jnm2 commented on src/Shouldly/ShouldlyExtensionMethods/ShouldBe/ObjectGraphTestExtensions.cs
> +                    throw new NotSupportedException("Comparing types that have indexers is not supported");
Nit: could you add a period to make this user-facing message a complete sentence?

2021-03-22 16:59 UTC, jnm2 approved these changes
Awesome! Thank you so much for getting this done!

2021-03-22 17:03 UTC, jnm2 commented
Uh oh, can't merge without resolving conflicts. Are you able to either rebase to fix the conflicts or merge the upstream master branch, creating a merge commit to fix the merge conflicts?

2021-03-22 17:05 UTC, closed without merging

2021-03-22 17:07 UTC, mcon commented
> Can you actually reopen and push/force push rather than starting a new PR? Thanks.

Slightly confused, looks like this is merged into master now, but the PR doesn't reflect that...

2021-03-22 17:12 UTC, jnm2 commented
Well look at that, that's weird. I did press the green Merge button, then the UI didn't refresh. I refreshed the page and it said it couldn't merge until conflicts were fixed, which I wasn't expecting. Looks like a UI glitch.

2021-03-22 17:14 UTC, jnm2 commented
Sorry about that. I guess no further action is necessary. If it bothers you that the PR appears to have been closed instead of merged, I'm willing to try to figure out how to reverse all this and merge properly. If not, I'll just put `[GitHub bug, actually merged]` in the PR title so I don't get confused when looking back.

2021-03-22 17:18 UTC, mcon commented
Yeah, feels like some sort of GH bug... I would bother looking into it unless it happens again, modifying the title to avoid confusion sounds like the way to go.

Thanks for the review!

2021-03-22 17:24 UTC, jnm2 commented
I submitted a GitHub support ticket in case this PR is useful for them in tracking down a bug.

2021-05-02 23:53 UTC, jnm2 commented
Response:

> Thanks for your patience while we worked on this!
> 
> Our engineers have investigated this issue and determined that the mobile aspect here appears to be a red herring.
> 
> The pull request got into a bad state from a partial merge action in the application which can occur, albeit infrequently, for various reasons. The team are working on better ways to manage this error going forward, but I'm afraid we are unable to manipulate the current state of the pull request.
> 
> If you do experience this issue again please do let us know.