Update to .NET 6, remove dependencies on EmptyFiles and DiffEngine
shouldly/shouldly pull request #937
Opened 2024-03-06 02:29 UTC by ddezinski

2024-03-09 16:43 UTC, sungam3r commented on src/Shouldly/Shouldly.csproj
> +    <RepositoryUrl>https://github.com/ddezinski/shouldly.git</RepositoryUrl>
```suggestion
    <RepositoryUrl>https://github.com/shouldly/shouldly.git</RepositoryUrl>
```

2024-03-09 16:43 UTC, sungam3r commented on src/Shouldly/Shouldly.csproj
> +    <PackageReleaseNotes>https://github.com/ddezinski/shouldly/releases/tag/$(Version)</PackageReleaseNotes>
```suggestion
    <PackageReleaseNotes>https://github.com/shouldly/shouldly/releases/tag/$(Version)</PackageReleaseNotes>
```

2024-03-09 18:20 UTC, slang25 requested changes
Let's not remove core functionality without some kind of discussion.

2024-03-10 00:01 UTC, ddezinski commented
Sorry I did not mean to send a pull request to the shouldly branch, I'm working on my own fork.  I don't use the DiffEngine or EmptyFiles functionality and these extra packages just add additional work to keep them up to date.  It would be great if these packages were optional or if there were two NuGet packages one with for those who need them and one without for those of us who do not.

2024-03-10 18:25 UTC, sungam3r commented
I would also remove these dependencies.

2024-05-30 10:55 UTC, SimonCropp commented
here is the PR that added diffengine if u want to revert it. https://github.com/shouldly/shouldly/pull/644

2024-05-30 12:11 UTC, slang25 commented
> here is the PR that added diffengine if u want to revert it. #644

I don't think it should be removed from the official Shouldly repo, however I am thinking it should be a separate package (that adopts the same TFM strategy as DiffEngine), and be enabled with a one-liner config.

This keeps the deps down, and doesn't could binary concerns like TFM support. I think this would keep most people happy.

2024-05-30 12:36 UTC, SimonCropp commented
what TFMs are you trying to maintain support for?

2024-05-30 12:46 UTC, slang25 commented
`netstandard2.0` in this case, but in general they are different projects with different strategies on TFM support, which the dependency version management more difficult. We're not the only package in the .NET ecosystem with this problem of course.

2024-05-30 12:54 UTC, SimonCropp commented
> netstandard2.0 

but the consumers of shoudly are test apps. which have to target a runtime. for example nunit has dropped support for netstandard. and the v3 xunit will be dropping support for netstandard.

2024-05-30 13:00 UTC, SimonCropp commented
side note: no objections to splitting the shoudly package

2024-08-31 03:39 UTC, Shane32 commented on src/Shouldly/Shouldly.csproj
> -    <PackageReference Include="EmptyFiles" Version="4.4.0" PrivateAssets="None" />
💯 👍 🥇

2024-08-31 03:51 UTC, Shane32 commented
> > netstandard2.0
> 
> but the consumers of shoudly are test apps. which have to target a runtime. for example nunit has dropped support for netstandard. and the v3 xunit will be dropping support for netstandard.

I'm exceedingly thankful that this library targets .NET Standard 2.0.

2024-11-17 08:53 UTC, sungam3r commented on src/Shouldly/Shouldly.csproj
> -    <PackageReference Include="EmptyFiles" Version="4.4.0" PrivateAssets="None" />
So do I

2025-03-20 22:41 UTC, SimonCropp commented
replaced by https://github.com/shouldly/shouldly/pull/1081

2025-03-20 22:41 UTC, closed without merging